version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: "
    ignore:
      - dependency-name: "python"
        update-types:
          - "version-update:semver-minor"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      devcontainers:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix: "
    groups:
      uv:
        patterns:
          - "*"
