name: Automerge PR

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/automerger-prs.yml@280eb47de8dbc07057815ace51460ac297a98093 # v1.0.1
    secrets: inherit
