name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'
      - 'beta'

permissions:
  actions: write
  contents: write
  issues: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@a81ca4777385c3138bc4491e1a1e98c4572aca5a # v1.0.6
    secrets: inherit
