name: Build Image on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-image-pr.yml@7b2d2e74a1e5e78eaa00680703479a72f3cef661 # v1.0.2
