name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'

permissions:
  actions: write
  contents: write
  issues: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@b8b611b97b8e3a6dd39d55bb5ae8a5f668e5aa1e # v1.0.1
