name: Create Release, Build and Deploy Image

on:
 push:
    branches:
      - 'main'
      - 'beta'

permissions:
  actions: write
  contents: write
  issues: write
  id-token: write
  pull-requests: write

jobs:
  build-and-release-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-and-push-image.yml@610af216f4fc39cf4435222deeb153006aee2fca # v1.0.5
    secrets: inherit
