name: Build Image on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-image-pr.yml@8bd6f9abef2d5a7e91aa37f08c46a483f917879f # v1.0.19
