name: Build Image on PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/build-image-pr.yml@280eb47de8dbc07057815ace51460ac297a98093 # v1.0.0
