name: MegaLinter

on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-image:
    uses: tkhom3/gha-workflows/.github/workflows/megalinter.yml@main
