name: Security Scans

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  scan-with-trivy:
    uses: tkhom3/gha-workflows/.github/workflows/scan-with-trivy-pr.yml@main
  scan-with-codacy:
    uses: tkhom3/gha-workflows/.github/workflows/scan-with-codacy-pr.yml@main
